version: '3'

services:
  app:
    build: .
    container_name: nest_app
    command: yarn start:dev
    depends_on:
      - db
    volumes:
      - .:/usr/app
    ports:
      - 3002:3002

  db:
    image: mysql
    container_name: nest_database
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=nest
    ports:
      - 3308:3306
